### ISSUE TITLE
Add failure case of missing horizontal strip of tiles to the README

### ISSUE THREAD

**Issue by daltonclaybrook** [mattcurrie/cgb-acid2#2]
I'm posting this issue out of a bit of selfishness because I have a failure case that's not represented on the README and I'm not quite sure what's going on. See the following image:

![dmg-vs-cgb](https://user-images.githubusercontent.com/1727803/109247998-f9935b00-77b2-11eb-8c9b-0711895d5e40.png)

On the left is my emulator, and on the right is SameBoy. The top images are running in DMG mode, and the bottom ones are running in CGB mode. It seems obvious (though it may not be) that the missing center tiles represent an unimplemented detail between DMG and CGB since this issue affects both emulators on DMG, but only affects my emulator on CGB. The problem is: I have no idea what that unimplemented detail is. If I manage to figure it out, I will reply to this issue with the fix and reiterate my recommendation to include this failure case in the README. If anyone else knows what's going on here, I would love to know the answer.

**Comment by mattcurrie** [comment]
Looks like that might be caused by bit 0 of LCDC being used to disable the background (DMG), instead of using it for master priority (CGB).

Let me know how you get on, and if that's the issue then I'll add it as a failure case :)

**Comment by daltonclaybrook** [comment]
You were right! Thanks for the great tip!

![working](https://user-images.githubusercontent.com/1727803/109256088-41ba7980-77c3-11eb-95f8-26aef63ddc21.png)

**Comment by mattcurrie** [comment]
Looking good! :)
